### ISSUE TITLE
Centos Base recommended?

### ISSUE THREAD

**Issue by dmadisetti** [XSEDE/singularity-nix-base#3]
Hi, was hoping to run some nix packaged code on Expanse. Would you recommend I use a Centos based container? I was planning on just using a nix based one.

Thanks!

**Comment by sk8forether** [comment]
Apologies for the delayed reply, this project is no longer maintained now that XSEDE has ended.

**Clarification:** These images _do_ use CentOS as a base OS, and only include the Nix package manager, not all of NixOS.  

However, please feel free to use these templates - though they are offered "as is" - if you feel they will be helpful to you.  You may also wish to contact Expanse help directly to see if they have any requirements for the containers run on their system.
